network:
  active: testnet
  profiles:
    # to deploy your own storage provider contract
    - name: testnet
      node: https://testnet-api.algonode.cloud
      node_token: ""
      app_id: 602746084
